apiVersion: v1
kind: Secret
metadata:
  name: flaskapi-secrets
type: Opaque
data:
  db_root_password: cm9vdA==      #root
  db_root_user: cm9vdA==          #root
  db_mysql: QnVja2V0TGlzdA==      #BucketList
  db_mysql_host: ZGI=             #db